package andersen.author_today;// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class AuthorTestTwo {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "D:\\Downloads\\tools\\chromedriver_win32\\chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void AuthorTestTwo() {
    driver.get("https://author.today/");
    driver.manage().window().setSize(new Dimension(1296, 696));
    driver.findElement(By.linkText("Войти")).click();
    driver.findElement(By.id("Login")).click();
    driver.findElement(By.id("Login")).sendKeys("aderstuganova@gmail.com");
    driver.findElement(By.cssSelector("div > form:nth-child(2)")).click();
    driver.findElement(By.name("Password")).sendKeys("19972002");
    Assert.assertEquals("Ошибка при вводе логина", "aderstuganova@gmail.com", driver.findElement(By.name("username")).getAttribute("value"));
    Assert.assertEquals("Ошибка при вводе пароля", "19972002", driver.findElement(By.name("password")).getAttribute("value"));
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector(".icon-bell-o")).click();
    driver.findElement(By.cssSelector(".avatar")).click();
    driver.findElement(By.cssSelector(".avatar")).click();
    driver.findElement(By.cssSelector(".avatar")).click();
    driver.findElement(By.linkText("Выйти")).click();
  }
}
