package andersen.author_today;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import org.junit.jupiter.api.Assertions;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class AuthorTestOne {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "D:\\Downloads\\tools\\chromedriver_win32\\chromedriver");
      driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void AuthorTestOne() {
    driver.get("https://author.today/");
    driver.manage().window().setSize(new Dimension(688, 680));
    {
      WebElement element = driver.findElement(By.linkText("Войти"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".brand-logo-img")).click();
    driver.findElement(By.linkText("Подборки произведений")).click();
    driver.findElement(By.cssSelector(".collection:nth-child(2) > .collection-title")).click();
    Assertions.assertEquals(driver.findElement(By.linkText("Апокалипсис. Постапокалипсис. Выживание")).getText(),"Апокалипсис. Постапокалипсис. Выживание");
  }
}
